name: skeleton_crew
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_sdl: ^0.10.0
  dart_style: ^2.2.3
  dart_synthizer: ^0.10.0
  file_picker: ^4.6.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  meta: ^1.8.0
  path: ^1.8.1
  path_provider: ^2.0.10
  shared_preferences: ^2.0.15
  short_uuids: ^2.0.0
  ziggurat: ^0.46.0
  ziggurat_sounds: ^0.26.0

dev_dependencies:
  analyzer: ^4.1.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
