name: skeleton_crew
description: Code generation for [Ziggurat](https://pub.dev/packages/ziggurat).

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dart_sdl: ^0.10.0
  dart_style: ^2.2.3
  dart_synthizer: ^0.11.1
  file_picker: ^5.0.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  meta: ^1.8.0
  path: ^1.8.1
  path_provider: ^2.0.11
  pubspec_parse: ^1.2.0
  shared_preferences: ^2.0.15
  short_uuids: ^2.0.0
  ziggurat: ^0.50.2

dev_dependencies:
  analyzer: ^4.3.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
